name: "Pull Request Labeler"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
  pull_request_review:
    types: [submitted]

jobs:
  call-labeler:
    uses: ulawil/common-wortkflows/.github/workflows/labeler.yml@main
    secrets:
      LABELER_TOKEN: ${{ secrets.LABELER_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
    
